Repository pknu-wap/2025-1-Web3-cuketmon, pull requests merged in 2025-04, with the labels that each got.

#113 [feat] 전투화면- 이미지 슬라이싱 추가
  cuketmon/public/BattlePage/animation/bug/highDamage1.png
  cuketmon/public/BattlePage/animation/bug/normalDamage1.png
  cuketmon/public/BattlePage/animation/electric/highDamage1.png
  cuketmon/public/BattlePage/animation/electric/normalDamage1.png
  cuketmon/public/BattlePage/animation/evil/highDamage1.png
  cuketmon/public/BattlePage/animation/fairy/highDamage1.png
  cuketmon/public/BattlePage/animation/fly/highDamage1.png
  cuketmon/public/BattlePage/animation/fly/normalDamage1.png
  cuketmon/public/BattlePage/animation/ground/highDamage1.png
  cuketmon/public/BattlePage/animation/ground/normalDamage1.png
  cuketmon/public/BattlePage/animation/ice/highDamage1.png
  cuketmon/public/BattlePage/animation/ice/normalDamage1.png
  cuketmon/public/BattlePage/animation/poison/highDamage1.png
  cuketmon/public/BattlePage/animation/poison/normalDamage1.png
  cuketmon/public/BattlePage/animation/psychic/highDamage1.png
  cuketmon/public/BattlePage/animation/water/highDamage1.png
  cuketmon/public/BattlePage/animation/water/normalDamage1.png
  cuketmon/src/Battle/Battle.js
Labels: battle page, 정승오, 진행 완료

#118 [test] damage계산 및 웹소켓 테스트 코드 구현
  BE/README.md
  BE/src/main/java/cuketmon/battle/TeamMaker.java
  BE/src/main/java/cuketmon/battle/dto/TrainerRequest.java
  BE/src/main/java/cuketmon/battle/service/BattleMatchService.java
  BE/src/main/java/cuketmon/damageclass/DamageClass.java
  BE/src/main/java/cuketmon/monster/entity/Monster.java
  BE/src/main/java/cuketmon/monster/service/MonsterService.java
  BE/src/main/java/cuketmon/skill/entity/Skill.java
  BE/src/main/java/cuketmon/skill/repository/SkillRepository.java
  BE/src/main/java/cuketmon/skill/service/SkillService.java
  BE/src/main/java/cuketmon/util/Damage.java
  BE/src/test/java/cuketmon/battle/service/BattleMatchServiceTest.java
  BE/src/test/java/cuketmon/skill/service/SkillServiceTest.java
  BE/src/test/java/cuketmon/util/DamageTest.java
Labels: 👤 조강래, .🔥 진행 중, '⚙️SERVER

#124 [feat] 메뉴바- hover 효과 추가 및 높이 조절
  cuketmon/src/Menubar/Menubar.css
  cuketmon/src/Menubar/Menubar.js
Labels: 👤 이찬이, .👍 진행 완료, '📱CLIENT

#126 [fix] 마이페이지, 랭킹 페이지- 반응형 오류 수정
  cuketmon/src/MyPage/MyPage.css
  cuketmon/src/Ranking/Ranking.css
  cuketmon/src/Ranking/Ranking.js
Labels: 🖥️ Ranking page, 👤 이찬이, .👍 진행 완료, '📱CLIENT

#129 [fix] 로그인 화면- 버튼 텍스트 오류 수정
  cuketmon/src/App.css
Labels: 🖥️ My page, 👤 이찬이, .👍 진행 완료, '📱CLIENT

#130 [feat] 생성화면- 모바일 반응형 구현
  cuketmon/public/MakePage/backgroundMobile.png
  cuketmon/src/Make/Make.css
  cuketmon/src/Make/Make.js
Labels: 🖥️ Cuketmon generate page, 👤 이찬이, .👍 진행 완료, '📱CLIENT

#131 [feat] - 전투화면 코드구조 개선
  cuketmon/public/BattlePage/animation/Game Boy Advance - Pokemon Emerald - Move Effects.png
  cuketmon/src/Battle/Battle.css
  cuketmon/src/Battle/Battle.js
Labels: 🖥️ Battle page, 👤 정승오, .👍 진행 완료

#138 [fix] 생성 페이지- 텍스트 크기 및 요소 위치 조정
  cuketmon/src/Make/Make.css
  cuketmon/src/Make/Make.js
  cuketmon/src/NamePage/NamePage.css
Labels: 👤 이찬이, .👍 진행 완료, 🖥️ Make page, '📱CLIENT

#120 [feat] Toy, Feed 유효성 검사 로직 분리
  BE/src/main/java/cuketmon/monster/entity/Monster.java
  BE/src/main/java/cuketmon/monster/service/MonsterService.java
  BE/src/main/java/cuketmon/trainer/embeddable/Feed.java
  BE/src/main/java/cuketmon/trainer/embeddable/Toy.java
  BE/src/main/java/cuketmon/trainer/entity/Trainer.java
  BE/src/main/java/cuketmon/trainer/service/TrainerService.java
  BE/src/test/java/cuketmon/monster/service/MonsterServiceTest.java
  BE/src/test/java/cuketmon/trainer/embeddable/FeedTest.java
  BE/src/test/java/cuketmon/trainer/embeddable/ToyTest.java
Labels: 👤 조강래, .🔥 진행 중, '⚙️SERVER

#137 [feat] 소셜 로그인 기능 구현
  BE/build.gradle
  BE/src/main/java/cuketmon/SecurityConfig.java
  BE/src/main/java/cuketmon/oauth/service/CustomOAuth2User.java
  BE/src/main/java/cuketmon/oauth/service/CustomOAuth2UserService.java
  BE/src/main/java/cuketmon/oauth/service/JwtAuthenticationFilter.java
  BE/src/main/java/cuketmon/oauth/service/OAuth2SuccessHandler.java
  BE/src/main/java/cuketmon/oauth/util/JwtUtil.java
  BE/src/main/java/cuketmon/trainer/controller/TrainerController.java
  BE/src/main/java/cuketmon/trainer/entity/Trainer.java
  BE/src/main/resources/application.properties
Labels: 👤 조강래, 👤 박현, .🔥 진행 중, '⚙️SERVER

#139 [fix] 연속된 머지로 인해 발생한 로직 오류 수정
  BE/src/main/java/cuketmon/oauth/service/CustomOAuth2UserService.java
Labels: 👤 조강래, .👍 진행 완료, '⚙️SERVER

#141 [feat] 로그인 화면- 카카오 로그인 연동
  cuketmon/src/App.css
  cuketmon/src/App.js
Labels: 🖥️ Login page, 👤 이찬이, .👍 진행 완료, '📱CLIENT

#142 [fix] local memory에서 테스트가 성공할 수 있도록 변경
  BE/src/test/java/cuketmon/TestDummyDataConfig.java
  BE/src/test/java/cuketmon/TestSkillDataConfig.java
  BE/src/test/java/cuketmon/battle/service/BattleMatchServiceTest.java
  BE/src/test/java/cuketmon/monster/service/MonsterServiceTest.java
  BE/src/test/java/cuketmon/skill/service/SkillServiceTest.java
  BE/src/test/java/cuketmon/util/DamageTest.java
Labels: 👤 조강래, .👍 진행 완료, '⚙️SERVER

#143 [fix] image 저장 타입 변경
  BE/src/main/java/cuketmon/monster/dto/MonsterDTO.java
  BE/src/main/java/cuketmon/monster/entity/Monster.java
Labels: 👤 조강래, .👍 진행 완료, '⚙️SERVER

#144 [feat] 생성페이지- 글자 수 조정 및 버튼 추가
  cuketmon/src/Make/Make.css
  cuketmon/src/Make/Make.js
  cuketmon/src/NamePage/NamePage.css
  cuketmon/src/NamePage/NamePage.js
Labels: 👤 이찬이, .👍 진행 완료, 🖥️ Make page, '📱CLIENT

#145 [feat] - 전투화면 진입/미세수정
  cuketmon/public/BattlePage/loadingcircle.png
  cuketmon/public/BattlePage/techselect.png
  cuketmon/src/App.css
  cuketmon/src/Battle/Battle.css
  cuketmon/src/Battle/Battle.js
  cuketmon/src/index.css
Labels: 🖥️ Battle page, 👤 정승오, .🔥 진행 중
