Repository pknu-wap/2025-1-Web3-cuketmon, pull requests merged in 2025-03, with the labels that each got.

#1 [feat] 로그인화면- UI/UX 구현
  cuketmon/.gitignore
  cuketmon/README.md
  cuketmon/package-lock.json
  cuketmon/package.json
  cuketmon/public/background1.png
  cuketmon/public/egg.png
  cuketmon/public/favicon.ico
  cuketmon/public/index.html
  cuketmon/public/logo192.png
  cuketmon/public/logo512.png
  cuketmon/public/manifest.json
  cuketmon/public/pocketmon_logo.png
  cuketmon/public/robots.txt
  cuketmon/src/App.css
  cuketmon/src/App.js
  cuketmon/src/App.test.js
  cuketmon/src/index.css
  cuketmon/src/index.js
  cuketmon/src/logo.svg
  cuketmon/src/reportWebVitals.js
  cuketmon/src/setupTests.js
Labels: Login page, 이찬이, 진행 중

#2 [feat] 로그인화면- Mobile UI/UX 구현
  cuketmon/public/background2.png
  cuketmon/src/App.css
Labels: Login page, 이찬이, 진행 중

#3 [fix] 로그인 화면- 라우터 오류 수정
  cuketmon/.gitignore
  cuketmon/README.md
  cuketmon/package.json
  cuketmon/src/App.css
  cuketmon/src/App.js
  cuketmon/src/MainRoutes.js
  cuketmon/src/Make.css
  cuketmon/src/Make.js
  cuketmon/src/index.js
Labels: Login page, 이찬이

#5 [fix] 로그인화면- 모바일 반응형 수정
  cuketmon/src/App.css
Labels: Login page, 이찬이

#6 [feat] 메뉴바- UIUX 구현
  cuketmon/public/battleicon.png
  cuketmon/public/mypageicon.png
  cuketmon/public/rankingicon.png
  cuketmon/src/Make.js
  cuketmon/src/menubar/Menubar.js
  cuketmon/src/menubar/menubar.css
Labels: 이찬이, 진행 중

#7 [feat] 메뉴바- 화면 이동 구현
  cuketmon/package-lock.json
  cuketmon/src/App.css
  cuketmon/src/MainRoutes.js
  cuketmon/src/battle.css
  cuketmon/src/battle.js
  cuketmon/src/menubar/Menubar.js
  cuketmon/src/mypage.css
  cuketmon/src/mypage.js
  cuketmon/src/ranking.css
  cuketmon/src/ranking.js
Labels: 이찬이, 진행 완료

#8 [fix] 메뉴바- css 수정
  cuketmon/src/menubar/menubar.css
Labels: 이찬이, 진행 완료

#9 [fix] 로그인화면- 반응형 오류 수정
  cuketmon/src/App.css
Labels: 이찬이, 진행 완료

#10 [fix] 로그인화면- 포켓몬 로고 위치 수정
  cuketmon/src/App.css
Labels: Login page, 이찬이, 진행 완료

#13 [feat] 마이페이지- desktop UI/UX 구현
  cuketmon/public/background3.jpg
  cuketmon/public/feed.png
  cuketmon/public/relevance.png
  cuketmon/public/toy.png
  cuketmon/src/mypage.css
  cuketmon/src/mypage.js
Labels: mypage, 이찬이, 진행 중

#14 [fix] 로그인 페이지- 버튼 수정
  cuketmon/src/App.css
Labels: Login page, 이찬이, 진행 완료

#15 [fix] 메뉴바- 버튼 테두리 변경
  cuketmon/src/menubar/menubar.css
Labels: 이찬이, 진행 완료

#16 [feat] 생성화면- 배경, 버튼 추가
  cuketmon/public/mk1background.png
  cuketmon/src/Make.css
  cuketmon/src/Make.js
Labels: 정승오, 진행 중, makepage

#19 [feat] Trainer가 지닌 장남감, 먹이 개수 확인 기능 구현
  BE/src/main/java/cuketmon/trainer/controller/TrainerController.java
  BE/src/main/java/cuketmon/trainer/dto/TrainerDTO.java
  BE/src/main/java/cuketmon/trainer/entity/Trainer.java
  BE/src/main/java/cuketmon/trainer/repository/TrainerRepository.java
  BE/src/main/java/cuketmon/trainer/service/TrainerService.java
Labels: 조강래

#21 [feat] 먹이주기, 놀아주기 기능 구현
  BE/src/main/java/cuketmon/monster/controller/MonsterController.java
  BE/src/main/java/cuketmon/monster/dto/MonsterDTO.java
  BE/src/main/java/cuketmon/monster/entity/Monster.java
  BE/src/main/java/cuketmon/monster/repository/MonsterRepository.java
  BE/src/main/java/cuketmon/monster/service/MonsterService.java
  BE/src/main/java/cuketmon/trainer/controller/TrainerController.java
  BE/src/main/java/cuketmon/trainer/entity/Trainer.java
Labels: 조강래

#23 [fix] 로그인화면- mobile UI/UX 수정
  cuketmon/src/App.css
Labels: Login page, 이찬이, 진행 완료

#24 [fix] 메뉴바- desktop UI/UX 수정
  cuketmon/public/battleicon.png
  cuketmon/public/egg.png
  cuketmon/public/mypageicon.png
  cuketmon/public/pocketmon_logo.png
  cuketmon/public/rankingicon.png
  cuketmon/src/menubar/menubar.css
Labels: Login page, 이찬이, 진행 완료

#26 [feat] 마이페이지- desktop UI/UX 구현
  cuketmon/public/cukemon_profile.png
  cuketmon/src/mypage.css
  cuketmon/src/mypage.js
Labels: mypage, 이찬이, 진행 완료

#29 [feat] 랭킹페이지- 기초 작업
  cuketmon/src/ranking.js
Labels: ranking page, 이찬이

#30 [fix] 랭킹페이지- 배경화면, 배틀 카운트 항목 추가
  cuketmon/public/RankingPage/background4.png
  cuketmon/src/ranking.js
Labels: ranking page, 이찬이, 진행 완료

#32 [feat] 랭킹페이지- desktop UI/UX 구현
  cuketmon/src/ranking.css
  cuketmon/src/ranking.js
Labels: ranking page, 이찬이, 진행 완료

#33 [fix] 랭킹화면- 랭킹 보드 위치 수정
  cuketmon/src/ranking.css
Labels: ranking page, 이찬이, 진행 완료

#34 [feat] 전투화면- 배경화면 적용
  cuketmon/public/BattlePage/battlebg.png
  cuketmon/public/BattlePage/cuketmonex.png
  cuketmon/src/Make.css
  cuketmon/src/Make.js
  cuketmon/src/battle.css
  cuketmon/src/battle.js
Labels: battle page, 정승오, 진행 중

#37 [feat] 마이페이지- 버튼 눌림 효과 추가
  cuketmon/src/mypage.css
Labels: mypage, 이찬이, 진행 완료

#38 [feat] skill api 받기 및 DB 저장 기능 구현
  BE/build.gradle
  BE/src/main/java/cuketmon/WebClientConfig.java
  BE/src/main/java/cuketmon/skill/SkillConfig.java
  BE/src/main/java/cuketmon/skill/controller/SkillController.java
  BE/src/main/java/cuketmon/skill/dto/AllSkillResponse.java
  BE/src/main/java/cuketmon/skill/dto/SkillDTO.java
  BE/src/main/java/cuketmon/skill/dto/SkillResponse.java
  BE/src/main/java/cuketmon/skill/entity/Skill.java
  BE/src/main/java/cuketmon/skill/repository/SkillRepository.java
  BE/src/main/java/cuketmon/skill/service/SkillService.java
  BE/src/main/resources/application.properties
Labels: 조강래, 진행 완료

#39 [fix] 전투화면- 이미지 표시오류
  cuketmon/src/battle.js
Labels: battle page, 정승오, 진행 완료

#41 [fix] 로그인화면- 버튼 위치 조정
  cuketmon/src/App.css
Labels: Login page, 이찬이, 진행 완료

#43 feat: type table 구현
  BE/src/main/java/cuketmon/skill/controller/SkillController.java
  BE/src/main/java/cuketmon/skill/dto/SkillResponse.java
  BE/src/main/java/cuketmon/skill/service/SkillService.java
  BE/src/main/java/cuketmon/trainer/repository/TrainerRepository.java
  BE/src/main/java/cuketmon/trainer/service/TrainerService.java
  BE/src/main/java/cuketmon/type/Type.java
  BE/src/main/java/cuketmon/type/TypeDamageTable.java
  BE/src/test/java/cuketmon/type/TypeDamageTableTest.java
Labels: 조강래, 진행 완료

#44 [feat] 전투화면- UI/UX 기초
  .gitignore
  cuketmon/public/BattlePage/HPbg.png
  cuketmon/public/BattlePage/stand.png
  cuketmon/public/BattlePage/techselect.png
  cuketmon/src/battle.css
  cuketmon/src/battle.js
  package-lock.json
  package.json
Labels: battle page, 정승오, 진행 중

#48 [feat] 생성화면- 기초 UI/UX 작업
  .gitignore
  cuketmon/public/MakePage/background4.png
  cuketmon/public/MakePage/type.png
  cuketmon/src/Make.css
  cuketmon/src/Make.js
  package-lock.json
  package.json
Labels: 이찬이, 진행 중, makepage

#50 [fix] skill 엔티티 필드 변경
  BE/src/main/java/cuketmon/skill/SkillConfig.java
  BE/src/main/java/cuketmon/skill/dto/AllSkillResponse.java
  BE/src/main/java/cuketmon/skill/dto/SkillResponse.java
  BE/src/main/java/cuketmon/skill/entity/Skill.java
  BE/src/main/java/cuketmon/skill/service/SkillService.java
Labels: 조강래, 진행 완료

#52 [feat] 생성화면- 기초 UI/UX 작업(2)
  cuketmon/public/MakePage/selectbackground.png
  cuketmon/public/MakePage/textareabackground.png
  cuketmon/src/Make.css
  cuketmon/src/Make.js
Labels: 이찬이, 진행 완료, makepage

#54 [fix] 전투화면- HP바 감소적용
  cuketmon/public/BattlePage/HPbar.png
  cuketmon/src/battle.css
  cuketmon/src/battle.js
Labels: battle page, 정승오, 진행 완료

#56 [feat] 생성결과페이지- 페이지 이동 구현
  cuketmon/src/MainRoutes.js
  cuketmon/src/Make.js
  cuketmon/src/MakeResult.css
  cuketmon/src/MakeResult.js
Labels: 이찬이, 진행 완료, makepage

#58 [feat] 생성결과화면- 배경화면 적용, 기초 UI/UX 작업
  cuketmon/public/MakeResultPage/MovingEgg.gif
  cuketmon/public/MakeResultPage/chatbox.png
  cuketmon/src/MakeResult.css
  cuketmon/src/MakeResult.js
Labels: 이찬이, 진행 완료, makepage

#59 [feat] 생성결과화면- 애니메이션 구현
  cuketmon/src/MakeResult.css
  cuketmon/src/MakeResult.js
Labels: 이찬이, 진행 완료, makepage

#60 [feat] 생성결과화면- 커켓몬 제작 실패 처리
  cuketmon/src/MakeResult.css
  cuketmon/src/MakeResult.js
Labels: 이찬이, 진행 완료, makepage

#61 [fix] 생성결과화면- 멘트 위치 수정
  cuketmon/src/MakeResult.css
Labels: 이찬이, 진행 완료, makepage

#63 [fix] 생성페이지-프롬프트 최대 입력 글자수 수정
  cuketmon/src/Make.js
Labels: 이찬이, 진행 완료, makepage

#64 [fix] 로그인화면-버튼 클릭 오류 수정
  cuketmon/src/App.css
  cuketmon/src/App.js
Labels: Login page, 이찬이, 진행 완료

#66 [feat] 커켓몬에게 스킬 부여 기능 구현
  BE/src/main/java/cuketmon/monster/entity/Monster.java
  BE/src/main/java/cuketmon/monster/service/MonsterService.java
  BE/src/main/java/cuketmon/skill/entity/Skill.java
  BE/src/main/java/cuketmon/skill/repository/SkillRepository.java
  BE/src/main/java/cuketmon/skill/service/SkillService.java
  BE/src/main/java/cuketmon/type/Type.java
  BE/src/test/java/cuketmon/skill/service/SkillServiceTest.java
Labels: 조강래, 진행 완료

#67 [fix] 마이페이지- 이미지 로딩 오류 해결
  cuketmon/public/MyPage/background3.png
  cuketmon/public/MyPage/backgroundmobile.png
  cuketmon/public/MyPage/cukemon_profile.png
  cuketmon/public/MyPage/feed.png
  cuketmon/public/MyPage/relevance.png
  cuketmon/public/MyPage/toy.png
  cuketmon/src/menubar/Menubar.js
  cuketmon/src/mypage.css
  cuketmon/src/mypage.js
Labels: mypage, 이찬이, 진행 완료

#68 [feat] 마이페이지- mobile 반응형 구현
  cuketmon/public/MyPage/background3mobile.png
  cuketmon/src/mypage.css
Labels: mypage, 이찬이, 진행 완료

#70 [fix] 클래스 이름 변경 및 파일 정리
  cuketmon/public/LoginPage/background1.png
  cuketmon/public/LoginPage/logo.png
  cuketmon/public/Menubar/battleicon.png
  cuketmon/public/Menubar/egg.png
  cuketmon/public/Menubar/mypageicon.png
  cuketmon/public/Menubar/rankingicon.png
  cuketmon/public/background2.png
  cuketmon/public/mk1background.png
  cuketmon/src/App.css
  cuketmon/src/App.js
  cuketmon/src/menubar/Menubar.js
  cuketmon/src/menubar/menubar.css
Labels: 이찬이, 진행 완료

#72 [fix] 생성페이지- 이미지 경로 수정 및 코드 최소화
  cuketmon/src/Make/Make.js
Labels: 이찬이, 진행 완료, makepage

#73 [fix] 마이페이지- 디폴트 이미지 삭제
  cuketmon/src/MyPage/MyPage.js
Labels: mypage, 이찬이, 진행 완료

#74 [feat] favicon 적용
  cuketmon/public/favicon.ico
Labels: 이찬이

#79 [feat] 커켓몬 이름 짓기 기능 구현
  BE/build.gradle
  BE/src/main/java/cuketmon/monster/controller/MonsterController.java
  BE/src/main/java/cuketmon/monster/dto/NamingDTO.java
  BE/src/main/java/cuketmon/monster/entity/Monster.java
  BE/src/main/java/cuketmon/monster/repository/MonsterRepository.java
  BE/src/main/java/cuketmon/monster/service/MonsterService.java
Labels: 조강래, 진행 완료

#80 [fix] 이름은 2자이상, 15자이하로 제한하도록 변경
  BE/src/main/java/cuketmon/monster/controller/MonsterController.java
  BE/src/main/java/cuketmon/monster/dto/NamingDTO.java
Labels: 조강래, 진행 완료

#81 [fix] 마이페이지- mobile 반응형 화면 크기 오류 해결
  cuketmon/src/Menubar/Menubar.css
  cuketmon/src/MyPage/MyPage.css
Labels: mypage, 이찬이, 진행 완료

#82 [fix] 메뉴바- Mobile 반응형 폰트 크기 조정
  cuketmon/src/Menubar/Menubar.css
Labels: 이찬이, 진행 완료

#83 [fix] 커켓몬 생성 후 해당 커켓몬의 id를 반환하도록 변경
  BE/src/main/java/cuketmon/monster/controller/MonsterController.java
  BE/src/main/java/cuketmon/monster/service/MonsterService.java
Labels: 조강래, 진행 완료

#87 [feat] 커켓몬 놓아주기 기능 구현
  BE/src/main/java/cuketmon/monster/controller/MonsterController.java
  BE/src/main/java/cuketmon/monster/service/MonsterService.java
Labels: 조강래, 진행 완료

#88 [feat] 전투화면- 애니메이션 로직
  cuketmon/src/battle.css
  cuketmon/src/battle.js
Labels: battle page, 정승오, 진행 중

#89 [fix] 마이페이지- 이미지 이름 수정
  cuketmon/public/MyPage/background.png
  cuketmon/public/MyPage/backgroundMobile.png
  cuketmon/public/MyPage/cukemonProfile.png
  cuketmon/public/MyPage/releaseButton.png
Labels: mypage, 이찬이

#90 [feat] 마이페이지- 커켓몬 삭제 버튼 추가
  cuketmon/src/MyPage/MyPage.css
  cuketmon/src/MyPage/MyPage.js
Labels: mypage, 이찬이, 진행 완료

#91 [feat] 랭킹페이지- Mobile 반응형 구현
  cuketmon/public/RankingPage/background.png
  cuketmon/public/RankingPage/backgroundMobile.png
  cuketmon/src/Ranking/Ranking.css
Labels: ranking page, 이찬이, 진행 완료

#92 [feat] 랭킹 페이지- 엔드포인트 추가
  cuketmon/src/Ranking/Ranking.js
Labels: ranking page, 이찬이, 진행 완료

#97 [feat] 웹 소켓 연결 기능 구현
  BE/build.gradle
  BE/src/main/java/cuketmon/WebConfig.java
  BE/src/main/java/cuketmon/battle/WebSocketConfig.java
  BE/src/main/java/cuketmon/battle/constant/BattleResult.java
  BE/src/main/java/cuketmon/battle/constant/BattleStatus.java
  BE/src/main/java/cuketmon/battle/controller/BattleController.java
  BE/src/main/java/cuketmon/battle/controller/BattleWebSocketController.java
  BE/src/main/java/cuketmon/battle/dto/BattleDTO.java
  BE/src/main/java/cuketmon/battle/dto/EndBattleResponse.java
  BE/src/main/java/cuketmon/battle/dto/MatchResponse.java
  BE/src/main/java/cuketmon/battle/dto/TrainerRequest.java
  BE/src/main/java/cuketmon/battle/entity/Battle.java
  BE/src/main/java/cuketmon/battle/repository/BattleRepository.java
  BE/src/main/java/cuketmon/battle/service/BattleMatchService.java
  BE/src/main/java/cuketmon/battle/service/BattleService.java
  BE/src/main/java/cuketmon/skill/service/SkillService.java
  BE/src/main/java/cuketmon/type/TypeDamageTable.java
  BE/src/test/java/cuketmon/skill/service/SkillServiceTest.java
Labels: 조강래, 진행 완료

#98 [feat] 전투화면- 피격효과 추가
  cuketmon/src/Battle/Battle.css
  cuketmon/src/Battle/Battle.js
Labels: battle page, 정승오, 진행 완료

#99 [feat] 마이페이지- 엔드포인트 추가
  cuketmon/src/MyPage/MyPage.js
Labels: mypage, 이찬이, 진행 완료

#100 [feat] 마이페이지- 백엔드 연동 작업
  cuketmon/.gitignore
  cuketmon/package-lock.json
  cuketmon/src/MyPage/MyPage.js
Labels: mypage, 이찬이, 진행 완료

#102 [fix] properties 파일 수정
  BE/src/main/resources/application.properties
  BE/src/test/java/cuketmon/skill/service/SkillServiceTest.java
Labels: 조강래, 진행 완료

#103 [chore] update .gitignore
  BE/.gitignore
Labels: 조강래, 진행 완료

#107 [feat] 커켓몬 조회 기능 구현
  BE/src/main/java/cuketmon/monster/controller/MonsterController.java
  BE/src/main/java/cuketmon/monster/dto/MonsterDTO.java
  BE/src/main/java/cuketmon/monster/service/MonsterService.java
Labels: 조강래, 진행 완료

#108 [feat] 전투화면- 기술추가, UI 수정
  cuketmon/public/BattlePage/animation/fire/high_damage1.png
  cuketmon/public/BattlePage/animation/fire/normal_damage1.png
  cuketmon/public/BattlePage/animation/grass/high_damage1.png
  cuketmon/public/Font/PokemonGSK2Mono.ttf
  cuketmon/src/Battle/Battle.css
  cuketmon/src/Battle/Battle.js
Labels: battle page, 정승오, 진행 중

#109 [feat] 마이페이지- 커켓몬 불러오기 연동
  cuketmon/src/MyPage/MyPage.js
Labels: mypage, 이찬이, 진행 완료

#110 [feat] 마이페이지-키보드 이벤트 재구현
  cuketmon/src/MyPage/MyPage.js
Labels: mypage, 이찬이, 진행 완료

#111 [feat] 웹소켓 연결 구현 및 테스트
  BE/src/main/java/cuketmon/WebClientConfig.java
  BE/src/main/java/cuketmon/battle/WebSocketConfig.java
  BE/src/main/java/cuketmon/battle/constant/BattleResult.java
  BE/src/main/java/cuketmon/battle/constant/BattleStatus.java
  BE/src/main/java/cuketmon/battle/controller/BattleWebSocketController.java
  BE/src/main/java/cuketmon/battle/service/BattleMatchService.java
  BE/src/main/java/cuketmon/monster/controller/MonsterController.java
Labels: 조강래, 진행 완료
